tiiuae/mesh_com

setup.py
`colcon build` command fails in `fog_sw` repo. This little fix make it pass
=> Compilation fix

modules/mesh_com/mesh_com/mesh_executor.py, modules/mesh_com/package.xml
- JSON configuration format checks added
- informative syslog output added for errors
- not crashing whole executor anymore with wrong JSON format
- mesh_com ROS node version changed to 0.3.2
=> mesh_com ROS node 0.3.2

common/core/os/ubuntu/wpa_supplicant/debian/config/wpasupplicant/linux, common/scripts/mesh-11s.sh, common/scripts/mesh-ibss.sh
11s:
- qca988x and ar9462 supported
- automatically detecting phy and device name
ibss:
- qca6174 and ar9462 supported
- automatically detecting phy and device name
=> Enable 11s for wpa_supplicant and wifi automatic detection for fogsw

modules/sc-mesh-secure-deployment/src/client-mesh.py, modules/sc-mesh-secure-deployment/src/mesh_com.conf, modules/sc-mesh-secure-deployment/src/server-mesh.py
Moved the client and server mesh configuration settings to a configuration file (rather than being hardcoded in json in server-mesh.py)
- Added 'type' to configuration (11s or ibss). The corresponding script is now copied over on the client.
- Added a 'debug' configuration setting
- Added some client conf for set_hostname and disable_networking (useful for running a client on a dev machine if you don't want to mess up the hostname/networking)
- Modified the way that the client gets the unencrypted json from the server by concatenating the list and parsing for json using regex. Allows unlimited # of fields to be addded/sent from the server.
=> User and mesh configuration is now taken from mesh_com.conf yaml file.

modules/mesh_com/debian/prerm, modules/mesh_com/package.xml
prerm script added to handle uninstallation ("dpkg -r ros-foxy-mesh-com" ).
Version number bumped.
=> mesh_com: debian removal script added

modules/mesh_com/mesh_com/mesh_subscriber.py
To verify that mesh_parameters are delivered reliably and the param message remains in the topic history even if the subscriber is create/established after the mesh_parameters message is published bu communication_link, the topic QoS settings needs to be defined to allow this behavior. As communication_link already publish to the topic with reliable way, the mesh_clom shall also subscribe the topic with same qos parameters to be able to read the message at all.
This PR changes the subscriber QoS to be align with Qos set by publisher in communication_link.
=> mesh_parameters subscriber qos change

modules/utils/monitor_phy_param.py, modules/utils/phy_param.conf
Add utility infra to capture or periodically monitor/log various
mac/phy parameter that includes radio rssi, CSI, BW, RF temperature,
PER, peer stats etc.
This change adds RSSI monitoring support on a given interface with
configurable periodicity.
uses:monitor_phy_param.py -r period -i interface
log file: /var/logs/rssi2021-06-29 10:53:34.833729.txt
=> mesh_com:utils: Add phy parameter monitoring utility infra

common/scripts/mesh-11s.sh
- Needs mesh_com wpa_supplicant which supports mesh_fwding config
parsing or openwrt version of wpa_supplicant.
- qca6174 added to supported wifi cards list.  Needs new firmware
=> mesh_fwding added to mesh-11s.sh script 

common/scripts/mesh-11s.sh, common/scripts/mesh-ibss.sh, modules/mesh_com/mesh_com/src/batstat.py, modules/mesh_com/package.xml
batstat crash fix.  Noise value availability check was not correct.
- minor comment fix
- mesh-11s.sh and mesh-ibss.sh wpa_supplicant logging added
Bug-Id: DP-1348 (internal system)
=> mesh_com: device_noise_dict KeyError crash fix

modules/sc-mesh-secure-deployment/install.sh
Update only required submodule as some of the
unused submodule update is causing failure in cloning of
required submodules.
=> mesh_com: Update only cryptolib submodule

common/tests/functional/check_BSS_list.sh, common/tests/functional/check_channel_list.sh, common/tests/functional/common.sh, common/tests/functional/common/common.sh, common/tests/functional/template.sh, common/tests/functional/test_mesh_connection.sh
test_mesh_connection.sh:
- can be used for NONE/SAE and 2.4GHz/5GHz
- can be used between Mesh nodes, single hop and beyond
- Network topology needs to be handled by tester (no VLAN in use) (separate script coming for chaining with VLAN)
Example:
- DUT responsible for running test:
`sudo ./test_mesh_connection.sh -i 192.168.1.y -e NONE -f 2412 -m client -s 192.168.1.x`
- DUTs respnsible to be part of the network(node):
`sudo ./test_mesh_connection.sh -i 192.168.1.x -e NONE -f 2412 -m server`
```
Usage: sudo ./test_mesh_connection.sh [-i ipaddress] [-e encryption] [-f freq] [-m mode] [-c country] [-o orig_int] [-r ra] [-h]
-i ipaddress    IP address to be used for node
-e encryption   SAE or NONE
-f frequency    Wi-Fi frequency in MHz
-c country      2-letter country code e.g. fi, ae, us.. …
```
=> Multipurpose Mesh test case added

common/tests/functional/check_BSS_list.sh, common/tests/functional/check_channel_list.sh, common/tests/functional/common/common.sh, common/tests/functional/common/deinit.sh, common/tests/functional/common/init.sh, common/tests/functional/template/template.sh, common/tests/functional/test_mesh_connection.sh
Now it is possible to build mesh node chains with VLAN when
testing multihops.
_init() and _deinit() functions moved to common/*init.sh.
=> Mesh VLAN support added

modules/sc-mesh-secure-deployment/src/gw/main.py
If both bat0 and br-lan had IP addresses configured,
it ended up to a state that IPv4 subnet function crashed.
Logic changed to check interfaces one by one.
related to #153
=> Fix GW monitoring script exiting error

modules/mesh_com/Dockerfile
FOG mission computer Docker containers are using the same base image. This component needs to use the same base image.
Benefits:
- Updates are synchronized
- Less resources used by containers (hard disk, bandwidth)
- Faster updates
=> Use fog-ros-baseimage in Docker image

common/scripts/mesh-ibss.sh
Add support for Doodle Labs Qualcomm Atheros: QCA9590-BR4B wireless card
=> Add support for Doodle Labs Qualcomm Atheros: QCA9590-BR4B wireless card

common/tools/field_test_log_plotter/README.md, common/tools/field_test_log_plotter/ftl_plotter.py
It is now possible to define what all figures are generated and how for example signal strength and throughput figures are plotted. Signal strength/throughput figures can be plotted as a function of time, distance or total distance and it is also possible to select slice of a dataframe to be plotted. See README.md for further info.
=> Add various control options to Field test log plotter tool

common/tools/field_test_log_plotter/ftl_plotter.py
Label names fixed in RX throughput figures. Y-axis value
scaling fixed in RX/TX throughput figures when bitrate
unit value gets below one due to chosen units.
Signed-off-by: Saku Auvinen <saku.auvinen@unikie.com>
=> Fix throughput figures plotting with small bitrate values

common/scripts/mesh-ibss.sh, modules/mesh_com/README.md, modules/mesh_com/entrypoint.sh, modules/mesh_com/mesh_com/mesh_executor.py
2 mesh networks (GS and Edge) support added. 
Default mesh enabled. 
Settings are based on manifest-defined environment variables.
```
initial-wifi:
edge:
api_version: 2
ssid: default-edge
key: "foobar"
enc: wep
ap_mac: "00:11:22:33:44:55"
country: cn
frequency: "5180"
ip: 192.168.1.10
subnet: 255.255.255.0
tx_power: "30"
mode: mesh
gs:
api_version: 2
ssid: default-gs
key: "foobar"
enc: wep
ap_mac: "00:11:22:33:44:55"
country: cn
frequency: "5745"
ip: 192.168.32.10
subnet: 255.255.255.0
tx_power: "30"
mode: mesh
```
=> 2 mesh networks (GS and Edge) support added

modules/mesh_com/Dockerfile, modules/mesh_com/Dockerfile.build_env
Already existing branches without this fix will fail to build due to ROS2 Galactic being end-of-life since 9.12.2022.
=> fog-ros-baseimage: include eol distros (galactic)

modules/utils/docker/entrypoint.sh, modules/utils/docker/start-docker.sh
Jira-ID: WC-210 mesh_com_1.0: Ethernet eth0 not bridged with mesh network
Detected HW version is brought visible inside docker by copying /etc/comms_pcb_version file into container-data. HW version is used to select what ethernet port is bridged with mesh network.
=> Bridge certain ethernet port with mesh network based on detected HW

modules/sc-mesh-secure-deployment/src/1_5/main.py, modules/sc-mesh-secure-deployment/src/1_5/main_with_menu.py
* main.py --> compute malicious node's mac address using the malicious node ID instead of security table index to avoid blocking the wrong node
* main_with_menu.py --> modified security beat to run every security beat period synchronously (previously it waited for a fixed period after a security beat completion to start the next beat, which may happen at different times for different nodes)
Jira_Id : MSS15-24
Signed-off-by: Selina Shrestha <selina.shrestha@tii.ae>
=> Fixed Security beat and Quarantine issues

modules/sc-mesh-secure-deployment/src/1_5/features.yaml, modules/sc-mesh-secure-deployment/src/1_5/features/continuous/server.py, modules/sc-mesh-secure-deployment/src/1_5/features/mutual/mutual.py, modules/sc-mesh-secure-deployment/src/1_5/main.py, modules/sc-mesh-secure-deployment/src/1_5/main_with_menu.py, modules/sc-mesh-secure-deployment/src/1_5/old_main.py
* features.yaml --> set secbeat: true
* main_with_menu.py --> Added functions sbeat_client(), sbeat_server() and modified sbeat() [port 6007 used to broadcast security beat]
* old_main.py --> Modified to call sbeat_client() if feature = 'secbeat'
* main.py --> continuous_authentication() modified to create new event loop if an event loop is not already present
* mutual.py --> Socket creation in send_password() modified to wait for 10 seconds in case of an exception [if sbeat coincides with MA, the socket needs to wait for a while]
* continuous/server.py --> reduced socket timeout in initiate_server() from 45 to 20 seconds in case the client is not responsive
Jira_Id : MSS15-28
Signed-off-by: Selina Shrestha <selina.shrestha@tii.ae>
=> Added Security Beat to Docker Execution

modules/sc-mesh-secure-deployment/src/1_5/common/mesh_utils.py, modules/sc-mesh-secure-deployment/src/1_5/features/continuous/utils.py, modules/sc-mesh-secure-deployment/src/1_5/features/utils/utils.py, modules/sc-mesh-secure-deployment/src/1_5/main_with_menu.py
* mesh_utils.py -> fixed get_neighbors_ip() to get IPs with last octets from 1 to 255 (previously only checked single digit IPs)
* main_with_menu.py --> computed broadcast IP for security beat automatically from bat0 IP, increased security beat period
* continuous/utils.py -> replaced calling get_neighbors_ip() multiple times with just once (as it is takes ~5 seconds each time)
* utils/utils.py -> increased exchange table socket timeout to 20 seconds from 15 seconds
Jira_Id : MSS15-30
Signed-off-by: Selina Shrestha <selina.shrestha@tii.ae>
=> Fixed issues in getting mesh neighbor IPs and automated security beat broadcast IP selection

modules/sc-mesh-secure-deployment/src/1_5/features.yaml, modules/sc-mesh-secure-deployment/src/1_5/features/continuous/server.py, modules/sc-mesh-secure-deployment/src/1_5/features/continuous/utils.py, modules/sc-mesh-secure-deployment/src/1_5/features/mba/mba.py, modules/sc-mesh-secure-deployment/src/1_5/features/mutual/mutual.py, modules/sc-mesh-secure-deployment/src/1_5/features/utils/utils.py, modules/sc-mesh-secure-deployment/src/1_5/header.py, modules/sc-mesh-secure-deployment/src/1_5/main.py, modules/sc-mesh-secure-deployment/src/1_5/main_with_menu.py
** features.yaml --> added provisioning as a feature 
** main_with_menu.py --> if provisioning is false use 24 bits hash of root_signature as mesh password, return sbeat_thread from sbeat_client() 
** main.py --> removed clause to check if security table is empty in only_ca() so that ca runs even after only_mesh, added clause to join sbeat_thread in main so that the script waits for security beat to complete before exiting during docker execution ** header.py --> added blake2b for hashing
** utils/utils.py --> increased exchange table socket timeout from 20 seconds to 25 seconds 
** mutual.py --> create table moved inside the Class, removed double read on line 161 
** mba.py --> changed indentations in client and server functions so that all the lines using sockets are inside the "with …
=> Fix only_mesh + security beat execution in docker, automatic password for only_mesh usage, bug fixes from code clean up

modules/mesh_com/Dockerfile
This baseimage update contains FastDDS SROS launch bugfix. Not going to be merged until it is tested on a drone.
=> [MERGE READY]-Bump tiiuae/fog-ros-baseimage from v2.0.0 to v2.1.0

common/tools/field_test_log_player/ftl_player.py
* ftl_player.py: 
- wrong drawing layout used with GPS info
- rx/tx label box columns header texts swapped
- fix support for new log format. "DCin (XT30)*" - columns dropped.
Jira-Id: WC-224
=> Fix ftl_player active path problems

modules/utils/docker/entrypoint.sh
Adding the sleep allows the AP to come up properly. Only needed for v1.0
=> Hotfix for issue with MCC startup in MS v1.0

modules/utils/docker/start-docker.sh
- container state check added before init
- container is initialised, if:
- for some reason not started by dockerd
- first boot --> never started before
Jira-Id: WC-225
Fix #274
=> Fix container double start/reset

modules/utils/docker/mcc_settings.sh
Use mesh.conf MCC_CHANNEL and automatic band calculation rather than hardcoding MCC AP to "g" and "7".
=> Fix hardcoded MCC AP channel and band.

common/scripts/mesh-11s.sh, modules/utils/docker/bridge_settings.sh, modules/utils/docker/entrypoint.sh, modules/utils/docker/mcc_settings.sh
Set bat0 and br-lan MTUs to 1500 rather than 1460. This fixes end to end connectivity between connected devices (e.g., laptops/phones) on the AP or eth bridge (using 1460 only allows laptop->csl->csl.....).
=> Fix e2e connectivity between laptop->csl->csl->laptop.

modules/utils/docker/start-docker.sh
- docker image was imported in every device startup
bugfix #277
Successfully already used and tested in nats_integration branch.
=> Fix docker image import

modules/utils/docker/entrypoint.sh
1) Remove platform check to start the mesh mode to support multiple platforms. S9011sMesh service has already the supported radio check based on PCI device ID. 
2) Remove deprecated ibss mesh mode service start.
=> mesh_com: remove CM4 platform check for mesh service to be started in multiple platforms(CM4, saplukiPI ..)

.github/workflows/tii-mesh-com.yaml, modules/utils/docker/entrypoint.sh, modules/utils/package/README.md
Updated the following python packages in modules/utils/package/:
* certifi --> v 2022.5.18.1 to 2022.12.7
* Pillow --> v 9.1.1 to 9.3.0
* cryptography --> v 39.0.0 to 39.0.1
* xgboost --> v 1.6.1 to 1.7.0
* scipy --> v 1.8.1 to 1.10.1
* torch --> v 1.11.0 to 1.13.1
* joblib --> v 1.1.0 to 1.2.0
* setuptools --> v 62.6.0 to 65.5.1
modules/sc-mesh-secure-deployment/src/1_5/main.py is running fine for MS 1.5
=> Python packages updates

modules/utils/docker/entrypoint.sh, modules/utils/docker/mcc_settings.sh
To summarize our changes : 
1- we assigned a static IP address on the wlp1s0 interface to 192.168.11.  for the QoS-OLSR 
2- we  assigned a SUB NET  for QoS-OLSR or the br-lan to allow routing with the AP
3- we allowed QoS-OLSR to route on IPV4 or IPV6
4- we allowed QoS_OLSR to run on the background and to write into the configuration file OLSRD.conf
=> QoS OLSR v2

common/tools/field_test_logger/S95logger, common/tools/field_test_logger/field_test_logger.py, common/tools/field_test_logger/infoparser.py, common/tools/field_test_logger/wifi_info.py
Update new sensors to field_test_logger and other enhancements
- New sensors added
- Arguments handling refactored and new arguments added:
-u = suffix to the log file name (default: "")
-i = network interface used in logging (default: wlp1s0)
-b = batman interface used in logging (default: bat0)
- error handling added, if max17260 not connected.  This flooded system log with HW without the max-chip.
=> Update new sensors to field_test_logger and other enhancements

common/scripts/mesh-11s_nats.sh, modules/sc-mesh-secure-deployment/src/nats/scripts/cli_settings_request.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py, modules/sc-mesh-secure-deployment/src/nats/src/validation.py
Adds configurability support to enable/disable a feature.  Currently creates a configuration item, but it is not yet used.
Jira-Id: WC-264
=> Add comms.setting support for MPTCP enable/disable

common/scripts/mesh-11s_nats.sh, common/scripts/mesh-helper.sh, modules/sc-mesh-secure-deployment/src/nats/scripts/cli_settings_request.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py, modules/sc-mesh-secure-deployment/src/nats/src/validation.py
Include comms.setting support for MPTCP.
Make BRIDGE as radio specific config from global config
Handling new parameter MPTCP
Updating radio pararmeters in MPTCP configuration
Support for multiple batman instances (bridged/non-bridged)
=> Include comms.setting support for MPTCP. 

modules/utils/docker/entrypoint_nats.sh, modules/utils/package/install_dependencies.sh
Installing torch-1.13.1
- This package is required for jamming avoidance and LDPI (IDS)
- It cannot be installed via buildroot as the source code is not available
=> Pytorch package installation

modules/sc-mesh-secure-deployment/src/nats/scripts/cli_settings_request.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py, modules/sc-mesh-secure-deployment/src/nats/src/validation.py
I have tested this changes as follow:
```
root@br_hardened:~# /opt/S90mdm_agent start
-k /etc/ssl/private/csl1.local.key -c /etc/ssl/certs/csl1.local.crt -r /etc/ssl/certs/ca.crt --agent mdm
Starting comms_nats_controller.py: OK
root@br_hardened:~# cat /opt/mdm_agent.log
2023-11-16 09:16:24,574 :: comms.status 0     :: DEBUG    :: mesh_cfg_status=MESH_CONFIGURATION_NOT_STORED, is_mission_cfg=False,
2023-11-16 09:16:24,603 :: comms.status 0     :: DEBUG    :: wpa_supplicant PID: 1616
2023-11-16 09:16:24,622 :: comms.status 0     :: DEBUG    :: interface=wlp1s0
2023-11-16 09:16:24,623 :: comms.status 0     :: DEBUG    :: bssid=00:00:00:00:00:00
2023-11-16 09:16:24,623 :: comms.status 0     :: DEBUG    :: freq=5805
2023-11-16 09:16:24,623 :: comms.status 0     :: DEBUG    :: ssid=gold …
```
=> MDM SLAAC integration

common/scripts/mesh-11s_nats.sh, common/scripts/qos_olsrd_conf.sh, common/tests/functional/Test-throughput.sh, modules/utils/docker/entrypoint.sh
The change can be summarized as below: 
1) Run Qos-Olsr on the mesh mode, having a function to start and stop QoS-OLSR
2) Make it work on the IPV6
=> To enable QoS-OLSR in MS2.0

modules/utils/package/install_dependencies.sh
Installing Pypcap package
- This package is required for LDPI (IDS)
- To install pypcap and its dependencies via buildroot python 2 needs to be installed, this will cause overhead/ performance issues. Instead, pypcap will be installed post-image build using its precompiled binary.
=> Pypcap package installation

modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py, modules/sc-mesh-secure-deployment/src/nats/debug_tests/README.md, modules/sc-mesh-secure-deployment/src/nats/debug_tests/client.py, modules/sc-mesh-secure-deployment/src/nats/debug_tests/config.py, modules/sc-mesh-secure-deployment/src/nats/debug_tests/test_debug.py, modules/sc-mesh-secure-deployment/src/nats/examples/cli_command_debug.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_command.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_common.py
Hi!
In this PR I introduce DEBUG COMMAND which can run any subprocess via comms_controller requests.
It is disabled by default.
MDM agent requests MDM server for `debug_conf` and store it to `/opt/debug_config.json`
I will create PR for server side soon.
This config looks like:
```
{"version":0,"payload":{"api_version":1,"role":"sleeve","debug_conf":[{"debug_mode":"disabled","rsyslog_addr":"172.25.26.140"}]}}
```
or
```
{"version":0,"payload":{"api_version":1,"role":"sleeve","debug_conf":[{"debug_mode":"enabled","rsyslog_addr":"172.25.26.140"}]}}
```
If `debug_mode` is `enabled` it is possible to use DEBUG COMMAND.
I have added `cli example` accordingly.
I also use this DEBUG COMMAND to test SLAAC in `debug_tests` folder.
=> debug command and SLAAC test

modules/utils/package/install_dependencies.sh
Installing scipy and scikit-learn packages
- Scipy package is required for LDPI (IDS) and PHY-CRA/ RSS
- Scikit-learn is required for LDPI
- The scipy package was not successfully installing via buildroot, instead it will be installed upon device boot-up (scikit-learn depends on scipy so it will be installed upon-device boot up as well). I will continue trying to integrate scipy and scikit-learn via buildroot but until then this approach will be used.
- This installation is for aarch64, similarly these packages need to integrated for riscv.
=> Install scipy and scikit-learn packages

common/scripts/mesh-11s_nats.sh, modules/sc-mesh-secure-deployment/src/2_0/features/mptcp/mptcp.sh, modules/sc-mesh-secure-deployment/src/nats/initd/S90mptcp, modules/sc-mesh-secure-deployment/src/nats/src/comms_command.py, modules/utils/docker/entrypoint_nats.sh
https://github.com/tiiuae/tc_distro/pull/139 - dependent PR
Initd script for MPTCP
Starting S90mptcp process if required
MPTCP script for configuring routing rules and starting the proxy server
=> Feature/mptcpv1 - MPTCP scripts and integration into mesh schield

common/tests/functional/test_osf.sh
Minor update to stop using the old fd0X addressing and start using the IPv6 address assigned to tun0.
=> Update OSF test script to check for and use latest IPv6 addressing scheme

modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/monitoring_wpa.py
This PR adds a 1 second delay to prevent high CPU usage due to polling a non-blocking socket :building_construction: 
Jira-Id: SECO-3343
=> CBMA High CPU Usage Fix

common/scripts/mesh-11s_nats.sh
Due to latest halow nrc driver update, some of the default values are changed. To make it same as previous version, we need to apply these settings.
=> SECO-3123: nrc1.5.0 update - setting long guard interval and support_ch_width

common/tests/functional/test_cbma/cbma_check_enabled.sh, common/tests/functional/test_cbma/cbma_check_lower_running.sh, common/tests/functional/test_cbma/cbma_check_running.sh, common/tests/functional/test_cbma/cbma_check_upper_running.sh
The title :arrow_up_small: 
The tests check that:
- CBMA is enabled by checking `features.yaml` (temporarily until it's part of the core)
- CBMA is running by checking that its server is listening on the specified ports
The tests assume that CBMA is launched by the `comms_nat_controller.py` script :t-rex: 
Jira-ID: SECO-2687
=> Add Basic Acceptance tests for CBMA

common/tests/functional/test_ldpi/sniffer_test.py, common/tests/functional/test_ldpi/trained_model_test.py, modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/ldpi/inference.py, modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/options.py, modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/tests/sniffer_test.py, modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/tests/trained_model_test.py
Changes:
- Updated sniffer_test.py (include mac addresses in flow tuple, change mock_eth to Ethernet frame instance (mock not iterable), update file imports paths to automatically execute pytest)
- Updated trained_model_test.py (configure stored models' paths, specify compatible torch device to load models on comms devices)
- Add test files to required file path
=> Update LDPI test files

modules/sc-mesh-secure-deployment/src/nats/mdm_agent.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_service_discovery.py
This PR enables IPv6 support in the Zeroconf Python module.
Unless explicitly stated at the object creation, Zeroconf is IPv4 only if not passing an interface that has an IPv6 address. Relevant function in Zeroconf code is `autodetect_ip_version()`
Also, timeouts for connecting to the MDM Server have been increased from 2 to 20 seconds, as the devices might fail to do upload/downloads on slow/unstable networks
:1st_place_medal:
=> MDM Agent Zeroconf IPv6 Support

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
=> Fix crash in MDM agent caused by interface no name

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
This PR fixes a regression introduced in https://github.com/tiiuae/mesh_com/pull/429 that prevented the assignment of global IPv6 addresses on MDM agent startup :adhesive_bandage:
=> Fix missing index variable in MDM Agent Global IPv6 assignment

.github/workflows/version.yaml
This PR adds the same functionality used in CBMA repo for the autocreation of a VERSION file containing the commit hash and timestamps on every commit done to the develop and main branches :secret:
=> Add Github workflow to autocreate VERSION files on main and develop

modules/sc-mesh-secure-deployment/src/nats/cbma/scripts/mess/cleanup_mess.sh, modules/sc-mesh-secure-deployment/src/nats/cbma/scripts/mess/create_bridge.sh, modules/sc-mesh-secure-deployment/src/nats/cbma/scripts/mess/create_mess.sh
(Redoing the PR notably because I mistakenly created https://github.com/tiiuae/mesh_com/pull/454 as a branch of a previous PR branch and don't want to risk messing with rebasing etc)
Traffic multiplication appears to be due to a regression in the Lower/Upper Mess Bridge's (lmb/umb) even though they appear to be correctly configured in terms of forwarding database (bridge fdb) and port isolation (ip -d link show) so here is a bruteforce hotfix just dropping any traffic that should not be happening anyway.
WARNING: untested with more than 2 devices (which is required to be able to reproduced the issue) as I do not have access to more than 2 right now, but FWIW this hotfix does not seem to break anything at least between 2 devices.
=> Mess bridge hotfix2

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
Now halow MTU is tried to set instead of printing error.
Jira-Id: SECO-5358
=> Change Halow MTU handling

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_if_monitor.py
The title :up: 
This fixes an exception (`NLM_F_DUMP_INTR`) raised by the kernel that happens in some cases when an interface is not yet ready.
According to the official documentation the fix is to try perform the operation again :raccoon: 
Relevant links:
- https://docs.kernel.org/core-api/netlink.html#support-dump-consistency
- https://docs.kernel.org/next/userspace-api/netlink/intro.html#dump-consistency
Jira-ID: SECO-6417
=> MDM Agent: Handle NetlinkDumpInterrupted except in ip.get_links()

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_if_monitor.py
The title :crown: 
In a previous PR, handling `NLM_F_DUMP_INTR` via `NetlinkDumpInterrupted` in pyroute2 was introduced, but this error handler is not available in pyroute2 0.5.7, so we are replacing it with the generic `NetlinkError`.
Also there seems to be some issue in not having the `halow` interface ready in CMs, so the timeout for this check has been increased to hopefully workaround this issue
:cd:
=> Fix old pyroute error + increase radio setup timeouts in MDM Agent

modules/sc-mesh-secure-deployment/src/nats/mdm_agent.py
The title :arrow_up: 
Change needed after upgrading the MDM Servers to use VRRP :mushroom: 
Edit:
Bit more context, if the mDNS resolution fails the fallback IPv6 will be used to resolve `defaultmdm.local` but then the certificate won't match, thus resulting in the following error:
> 2024-07-11 09:50:21,415 :: comms.controller.mdm_agent :: ERROR    :: HTTP request failed with error: HTTPSConnectionPool(host='fdbb:1ef7:9d6f:e05d::1', port=5000): Max retries exceeded with url: /public/get_device_config/mesh_conf?device_id=04f021bf893310000000744cf195 (Caused by SSLError(SSLCertVerificationError("hostname 'fdbb:1ef7:9d6f:e05d::1' doesn't match 'defaultmdm.local'")))
=> MDM Agent: Upgrade hardcoded fallback mDNS IPv6 to <prefix>::100

modules/sc-mesh-secure-deployment/src/nats/src/comms_if_monitor.py
The title :up: 
Apparently in some cases the call to IPRoute.get() might result in `No buffer space available`:
>   File "/opt/nats/src/comms_if_monitor.py", line 67, in monitor_interfaces
messages = self.__ipr.get()
>  File "/usr/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 376, in get
>  File "/usr/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 776, in get
>  File "/usr/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 554, in recv_ft
> OSError: [Errno 105] No buffer space available
To workaround this issue we are making the `bufsize` autodetectable.
It shall be noted that this feature seems to be broken in `pyroute2` version 0.7.12, but the versions included in iMX8 and RPIOS are lower, so a TODO has been added in the line for future …
=> MDM Agent: Use auto-calculated buffer size in IPRoute.get() call

common/scripts/mesh-11s_nats.sh
halow range is not good due to default lower mesh rssi threshold. Applying -105dbm as mesh rssi threshold
=> SECO-7322: mesh rssi threshold for halow to -105dbm

modules/sc-mesh-secure-deployment/src/nats/src/bat_ctrl_utils.py
bat0 OGM interval of 500ms is required to handle mobility use case. bat1 OGM remain as 5 sec.
=> SECO-7824: bat0 OGM interval to 500ms to handle mobility use cases

modules/sc-mesh-secure-deployment/src/nats/src/comms_service_discovery.py
If MDMServer port in mDNS response is None, keep listening for mDNS responses
-SECO-7799
=> MDMServer: handling of invalid port in mDNS response

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
-typo caused enum instead of string to be passed as key path
-SECO-7892
=> Fix typo that caused CBMA not to find upper CBMA private key path

modules/sc-mesh-secure-deployment/src/nats/conf/default_ms_config.yaml, modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
Jira-ID: SECO-8033, SECO-8006
Bridge control changed so that br-lan is not deleted when CBMA/MDM Agent is stopped. Also trying to use static MAC for the bridge using MAC from some physical interfaces (osf or ethernet) that is not configured to lower CBMA. Default configs changed so that eth0/end0/end or lan1 interface is added to bridge.
=> Change br-lan control

modules/sc-mesh-secure-deployment/src/nats/conf/default_ms_config.yaml, modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py, modules/sc-mesh-secure-deployment/src/nats/src/comms_service_refresh.py
Avahi workaround
Jira-Id: SECO-7551
=> Fix "IPv6 connection unreliable from external PC"

modules/sc-mesh-secure-deployment/src/nats/cbma/scripts/mess/constants.rc, modules/sc-mesh-secure-deployment/src/nats/conf/default_ms_config.yaml, modules/sc-mesh-secure-deployment/src/nats/src/constants.py
Jira-ID: SECO-9738
- Base MTU size changed from 1500 to 1372
- Default hostname changed from nixos to buildroot
=> Update base MTU size
