tiiuae/mesh_com

common/scripts/mesh-ap.sh
modules/sc-mesh-secure-deployment/configure.sh
modules/sc-mesh-secure-deployment/services/mesh@.service
modules/sc-mesh-secure-deployment/src/server-mesh.py

Minor fixes to mesh-tb persistence of APs and routes

Minor fixes to persist APs and default routes

---

common/scripts/mesh-11s.sh
common/scripts/mesh-ibss.sh
modules/mesh_com/debian/postinst
modules/mesh_com/mesh_com/mesh_executor.py
modules/mesh_com/mesh_com/mesh_publisher.py
modules/mesh_com/mesh_com/mesh_subscriber.py
modules/mesh_com/package.xml

- 11s support added to mesh_com ros node
- mesh-11s.sh updated to same level as ibss script (modes: mesh, ap, off)
- mesh_com python code refactoring
- api_version 1 for ibss and api_version 2 for 11s
- version update to 0.3.0

11s support added to node, +some refactoring

---

common/scripts/mesh-11s.sh
common/scripts/mesh-ibss.sh
modules/mesh_com/debian/postinst

- pci-mesh, usb-client
- Network Manager-unmanaged wifi interfaces defined wlp* and wlan*

handle pci and usb wifi cards in drone case

---

modules/mesh_com/mesh_com/mesh_executor.py
modules/mesh_com/package.xml

- bug found in long period testing
- version number changed to 0.3.1
Tested overnight by changing configuration in every 10 seconds with ROS Topic and no problems anymore.

bugfix: lost configuration package in rare cases

---

modules/mesh_com/mesh_com/mesh_publisher.py
modules/mesh_com/package.xml

Mesh Publisher debug print removed

Mesh Publisher debug print removed

---

common/scripts/mesh-11s.sh
common/scripts/mesh-ibss.sh

- enhancement to wifi device detection
- informative prints added
- currently few qualcomm radios are supported with automatic detection
- single mesh radio case currently only supported

wifi detection enhancement for mesh-11s and mesh-ibss scripts

---

.gitmodules

- this is NXP version of openwrt and using layerscape-20.09 release branch.

Openwrt as submodule

---

modules/sc-mesh-secure-deployment/configure.sh

IBSS and sta interface are not supported concurrently
with most of single radio(phyx). In order to allow sta
connection post mesh service is running, stop mesh(IBSS)
service on the selected interface if already running.

mesh_com: Fix STA connection issue post mesh configuration

---

common/scripts/mesh-11s-mr.sh

- created new script for multi-radio purposes
- 1st radio follows json frequency parameter and currently second radio is hardcoded to 2412MHz(channel 1)
- Support any number of selected Qualcomm PCI wifi cards (frequency distribution needs to be solved)
example:
sudo ./mesh-11s-mr.sh mesh 192.168.1.2 255.255.255.0 00:11:22:33:44:55 1234567890 mymesh2 5220 30 fi
or
sudo ./mesh-11s-mr.sh ap
or
sudo ./mesh-11s-mr.sh off

mesh_com: initial multi radio support script

---

modules/sc-mesh-secure-deployment/configure.sh

scan selected STA interface to make sure that user selects
available access point for reliablity.
Example:
sudo modules/sc-mesh-secure-deployment/configure.sh -ap
=== sc-mesh-secure-deployment-configure ===
> Do you wish to...
1) Connect to an Access Point?
2) Create an Access Point?
3) Remove an Access Point?
> Please choose from the list of available interfaces...
1) wlan0
> scanning available Access Point, select ssid from scan list...
1) Test	     3) JioFiber-2G
2) Paraskhush_2.4    4) Amal
- Password: xxxxxx

mesh_com: scan station interface for ssid selection

---

common/scripts/mesh-11s.sh
common/scripts/mesh-ibss.sh
modules/mesh_com/mesh_com/src/batstat.py
modules/mesh_com/package.xml

mesh_com: device_noise_dict KeyError crash fix
batstat crash fix.  Noise value availability check was not correct.
- minor comment fix
- mesh-11s.sh and mesh-ibss.sh wpa_supplicant logging added
Bug-Id: DP-1348 (internal system)

Develop to main

---

modules/sc-mesh-secure-deployment/services/initd/S90mesh

mesh_com: Fix startup issue for mesh init script

---

modules/utils/docker/Dockerfile

wpa_supplicant/hostapd install path selection based
on the cpu architecture.  wpa_supplicant with mesh_fwding
support and with CONFIG_MESH.

Docker with mesh enabled wpa_supplicant

---

modules/sc-mesh-secure-deployment/services/initd/S9011sMesh
modules/sc-mesh-secure-deployment/src/bash/conf-11s-mesh.sh
modules/sc-mesh-secure-deployment/src/client-mesh.py
modules/sc-mesh-secure-deployment/src/mesh_com_11s.conf

This series adds supports fixes to test 11s mesh_com(client server auth and 11s configuration onboarding from server).

mesh_com fixes for 11s radio

---

.github/workflows/main.yaml

Adding artefactory URL hotfix to 'develop' as well as 'main'

fix artifactory url

---

common/scripts/mesh-11s.sh

Better range with supported cards.
modprobe command checks added.

Range tweaks for 11s mesh

---

common/tests/functional/check_BSS_list.sh
common/tests/functional/check_channel_list.sh
common/tests/functional/common.sh
common/tests/functional/template.sh

First test case created for BSS scan and template file for new
cases.

Feature/tests - functional test cases

---

.github/workflows/main.yaml

replace jfrog cli usage with action

---

common/tests/security/deauth_attack.sh

Have changed based on previous reviews
* Extra comment on OUI reference
* Deinit called
* Wlan0 was changed to $interface
* Checked out to develop branch instead of main

Deauth attack script without result method

---

modules/utils/docker/entrypoint.sh

mesh_com: Add comms sleeve startup configurations

---

modules/sc-mesh-secure-deployment/configure.sh

Adding the CI-CD automation to configure.sh
Signed-off-by: Suhail <suhail@ssrc.tii.ae>

Added CI-CD part to configure.sh file for automation

---

modules/sc-mesh-secure-deployment/src/1.5/features/continuous/ca_main.py
modules/sc-mesh-secure-deployment/src/1.5/features/continuous/client.py
modules/sc-mesh-secure-deployment/src/1.5/features/continuous/server.py

Calling client and server for continuous authentication from main file

Ca mesh1.5 main

---

common/tools/field_test_log_plotter/README.md
common/tools/field_test_log_plotter/constants.py
common/tools/field_test_log_plotter/ftl_plotter.py
common/tools/field_test_log_plotter/requirements.txt

Signed-off-by: Saku Auvinen <saku.auvinen@unikie.com>

Add tool to generate graphs from field test logs.

---

modules/utils/docker/entrypoint.sh
modules/utils/package/README.txt

Added 2nd list of python packages
Signed-off-by: Monika-Research <monika.prakash@tii.ae>

Fixed pypcap installation

---

common/tools/field_test_logger/README.md

Add README.md file for field_test_logger - tool

---

modules/mesh_com/mesh_com/src/batadvvis.py
modules/mesh_com/mesh_com/src/batstat.py

- Too tight data collection loop, when delivering data every 10s.
data collection loop was every 0.1s and now 1s.  ( mesh_init_executor load drops from 49% to 9% )
- Some pylint warning fixes.

Fix performance issues with data collection loop

---

common/tools/field_test_logger/wifi_info.py

Fixed originators list logging.
Ref: WC-146 Bug in logging mesh originators list
Signed-off-by: Saku Auvinen <saku.auvinen@unikie.com>

Fix mesh originators list logging

---

common/tools/field_test_log_player/README.md
common/tools/field_test_log_player/ftl_player.py
common/tools/field_test_log_player/requirements.txt

Add tool to replay field test log files

---

common/scripts/mesh-11s.sh

- 11b rates support dropped
- fix shellcheck warnings

2.4GHz Mesh range enchancement

---

common/tools/field_test_logger/README.md
common/tools/field_test_logger/S95logger
common/tools/field_test_logger/field_test_logger.py

It is now possible to define suffix to field test log
file via command line argument.
Signed-off-by: Saku Auvinen <saku.auvinen@unikie.com>

Add possibility to define suffix for filename

---

common/tools/field_test_log_player/README.md
common/tools/field_test_log_player/ftl_player.py

Timestamp handling changes:
- Indoor usage  -> system timestamps
- Outdoor usage -> GPS timestamps.
More command line options added and pylint warning fixes.
Jira-Id: WC-147

Add data path visualisation to ftl_player

---

common/tools/field_test_log_player/ftl_player.py

Now throughput rx/tx throughput values are plotted from each node.
Some code refactoring done.

FTL player update

---

common/tools/field_test_logger/field_test_logger.py

1s logger loop accuracy before fix: 1.08-1.298
1s logger loop accuracy after fix: 1.00-1.001
Jira-Id: WC-152

Fix logger loop accuracy

---

common/tools/field_test_logger/field_test_logger.py
common/tools/field_test_logger/infoparser.py

- INA sensor I2C path changes.
- ability to search from I2C path options.
New DC power measurement support added.
Jira-Id: WC-155

Add CM1.5 support

---

modules/mesh_com/entrypoint.sh
modules/mesh_com/mesh_com/mesh_publisher.py
modules/mesh_com/mesh_com/mesh_subscriber.py

Entrypoint receives SIGTERM (from docker stop) and sends SIGINT to proper process to make ROS2 node to stop gracefully.
This prevents SROS authentication from breaking due to uncontrolled termination of the ROS2 node.

DO NOT MERGE, Docker sigterm fix

---

common/tools/field_test_log_plotter/constants.py
common/tools/field_test_log_plotter/ftl_plotter.py
common/tools/field_test_log_plotter/requirements.txt

* Fix html map generation. Plotter tool changed (and locked) to use ipyleaflet v. 0.17.0 
* Add DCin voltage/current figures plotting (Jira id: WC-158)
* Fix incorrect y-axis label in "voltage_and_current" plots
* Add missing y-axis labels to some rssi and throughput related plots

Field test log plotter improvements and bug fixes

---

common/tools/field_test_log_player/README.md
common/tools/field_test_log_player/ftl_player.py

- add support rewind/skip 30s slots
- text box legend about throughput statuses
- data path tracking fixes

Fix field test log player problems

---

modules/utils/docker/entrypoint.sh

Fixed OLSR configuration
IP address assigned to br-lan automated
Signed-off-by: Monika-Research <monika.prakash@tii.ae>

Including OLSR Configuration

---

common/scripts/mesh-11s.sh

Add option for qos-olsr routing protocol
Pipe output of qos-olsr and olsr to a log file in /tmp

Support qos-olsr and enable logging

---

common/tools/field_test_logger/infoparser.py

- Fix field_test_logger startup
- and minor comment fix
Jira-Id: WC-169

Fix field_test_logger startup

---

modules/mesh_com/Dockerfile
modules/mesh_com/Dockerfile.build_env

Fixing mesh_com build for feature/1.5 branch

---

common/tools/field_test_logger/field_test_logger.py
common/tools/field_test_logger/infoparser.py

field_test_logger: add more GPS data to log file

---

modules/utils/docker/entrypoint.sh

Signed-off-by: Monika-Research <monika.prakash@tii.ae>

Fixed sync issue encountered between soft AP and mesh in SCC config.

---

modules/sc-mesh-secure-deployment/src/1_5/header.py
modules/sc-mesh-secure-deployment/src/1_5/main.py
modules/sc-mesh-secure-deployment/src/1_5/main_with_menu.py
modules/utils/docker/entrypoint.sh

* main.py --> Modify main function to perform tasks performed by old_main.py (i.e mutual authentication and security beat)
* entrypoint.sh --> replace calling old_main.py by main.py
* header.py --> Import yaml package
Jira_Id : MSS15-28
Signed-off-by: Selina Shrestha <selina.shrestha@tii.ae>

Replace old_main.py by main.py

---

modules/sc-mesh-secure-deployment/src/1_5/main.py
modules/utils/docker/entrypoint.sh

* main.py --> added yaml on imports, commented start_servers function
* entrypoint.sh --> added bug_initialization function, and added random MeshIP and AuthAP IP addresses.
Jira_Id : MSS15-29

Automate Docker execution without user intervention

---

common/tools/field_test_log_plotter/ftl_plotter.py

Fix field test log plotter

---

modules/mesh_com/mesh_com/mesh_publisher.py
modules/mesh_com/mesh_com/src/batadvvis.py
modules/mesh_com/mesh_com/src/batstat.py

Add timestamp to visualization and change to 1Hz interval
Jira-Id: WC-211

do not merge, for testing purposes

---

common/tools/field_test_log_plotter/ftl_plotter.py

Add support for single antenna field test logs

---

common/tools/field_test_log_plotter/ftl_plotter.py

Field test log plotter changes for Jira ticker WC-219 cherry picked from mesh_com_1.0 based branch.

Add field test log plotter fixes to develop branch

---

.gitignore
modules/sc-mesh-secure-deployment/src/1_5/common/ConnectionMgr.py
modules/sc-mesh-secure-deployment/src/1_5/common/mesh_utils.py
modules/sc-mesh-secure-deployment/src/1_5/common/utils.py
modules/sc-mesh-secure-deployment/src/1_5/features/continuous/client.py
modules/sc-mesh-secure-deployment/src/1_5/features/continuous/server.py
modules/sc-mesh-secure-deployment/src/1_5/features/mba/mba.py
modules/sc-mesh-secure-deployment/src/1_5/features/mutual/mutual.py
modules/sc-mesh-secure-deployment/src/1_5/features/mutual/provServer/provServer.py
modules/sc-mesh-secure-deployment/src/1_5/features/mutual/utils/primitives.py
modules/sc-mesh-secure-deployment/src/1_5/features/mutual/utils/wifi_ssrc.py
modules/sc-mesh-secure-deployment/src/1_5/features/ness/driver.py
modules/sc-mesh-secure-deployment/src/1_5/features/utils/utils.py
modules/sc-mesh-secure-deployment/src/1_5/header.py
modules/sc-mesh-secure-deployment/src/1_5/main.py
modules/sc-mesh-secure-deployment/src/1_5/main_with_menu.py
modules/utils/docker/entrypoint.sh

** client.py --> use of "with" for the socket, remove comments ** ConnectionMgr.py --> use fprint on the declaration, restructure else, if on line 73 to make it cleaner. use of with for socket handling ** driver.py --> remove unnecessary if
** entrypoint.sh --> added clean_up function
** header.py --> added sec_beat constants
** main.py --> added sys on all exits, removing comments, redone indentation ** main_with_menu.py --> remove 'cli' unused on return (line 53), added sys.exit(), return none on exception, added new function sbeatcount for clean up ** mba.py --> added 'with' to handle sockets
** mesh_utils.py --> refactor get_mac_neighbors, use 'with' to handle sockets ** mutual.py --> moved create_table as outside static function, use 'with' to open/close files. Added function …

Code Review and cleanup

---

modules/mesh_com/Dockerfile.build_env

JFrog repository url updated in Dockerfile.build_env

Update JFrog repository url

---

.github/workflows/main.yaml
Makefile
README.md
build.sh
modules/mesh_com/Dockerfile
modules/mesh_com/Dockerfile.build_env
modules/mesh_com/debian/control.em
modules/mesh_com/entrypoint.sh
modules/mesh_com/mesh_com/mesh_executor.py
modules/mesh_com/package.sh

PR to solve this issue : https://github.com/tiiuae/mesh_com/issues/270

CherryPicked commits to enable upgrade to latest base image

---

modules/utils/docker/start-docker.sh

accidentally left original code outside the if-statement.
Jira-Id: WC-225

Fix container double start/reset (part2)

---

modules/mesh_com/Dockerfile
modules/mesh_com/entrypoint.sh
modules/mesh_com/setup.cfg

DP-6747 / DP-6746

---

modules/sc-mesh-secure-deployment/src/nats/src/comms_hsm_controller.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_provisioning.py

Jira-ID: SCDI-31
Logger is used instead of plain prints. Keypair algorithm can be defined via start parameter. Clearly wrong system time is updated using certificate info.

Refactor provisioning agent

---

modules/sc-mesh-secure-deployment/src/nats/comms_nats_discovery.py

Fix NATS start in unprovisioned device 

---

modules/sc-mesh-secure-deployment/src/nats/src/comms_provisioning.py

Fix provisioning agent crash

---

modules/sc-mesh-secure-deployment/src/2_0/features/jamming/util.py

The wpa_supplicant configuration file name has recently been changed, updated the jamming avoidance code to match changes

Updated wpa_supplicant file name to match latest changes

---

common/scripts/mesh-11s_nats.sh

Hot fix to get etho into a bridge

---

common/scripts/mesh-11s_nats.sh

Add SPI Halow support

---

modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authClient.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authServer.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/cert_generation/ca_side.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/cert_generation/client_side.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/cleanup_cbma.sh
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/macsec/macsec.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/multicast/multicast.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/mutauth.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/secure_channel/secchannel.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/utils.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/wpactrl.py

PR addressing all change requests (except for https://github.com/tiiuae/mesh_com/pull/337#pullrequestreview-1738374063) until https://github.com/tiiuae/mesh_com/pull/337#pullrequestreview-1739081705 :trophy:

CBMA changes requested in #337

---

common/scripts/mesh-11s_nats.sh
common/scripts/slaac.sh
modules/sc-mesh-secure-deployment/src/nats/initd/S90APoint

see https://ssrc.atlassian.net/browse/MSS20-257

SLAAC integration

---

common/tools/field_test_logger/wifi_info.py

Read rssi from HaLoW station dump as well. HaLoW only has one antenna and station dump does not contain the antenna specific list of rssi's.
Fetch MCS values with command 'cli_app show sta 0 all' when MCS info not found from iw dev station dump. For some reason halow MCS info is not included in there.

Field test logger halow support.

---

modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py

- certificate bundle upload
- features json to yaml support
- dead code removal
- styling changes and imports optimized

Certificate bundle upload to server

---

modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py
modules/utils/docker/entrypoint_nats.sh

Support these GET:
-  ConfigType.FEATURES
-  ConfigType.CERTIFICATES  ( tries to download, but server side is not yet providing certs )
-  ConfigType.MESH_CONFIG
-  ConfigType.DEBUG_CONFIG
Support these POST:
-  ConfigType.CERTIFICATES

MDM client 

---

modules/sc-mesh-secure-deployment/src/2_0/features.yaml
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authClient.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authServer.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/macsec/macsec.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/multicast/multicast.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/mutauth.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/secure_channel/secchannel.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/setup_cbma.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/utils.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/verification_tools.py
modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_if_monitor.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_service_discovery.py

Workaround for Jira-ID: SECO-513
Quick fixes for Jira-ID: SECO-312
PoC just to get starting point for further integration/development. Birth certificates are used with CBMA. CBMA feature is off by default as testing strategy should be planned first and it is likely to require design changes as well. Feature can be activate by setting CBMA flag as true in features.yaml.

Initial MDM agent cbma feature integration

---

modules/sc-mesh-secure-deployment/src/2_0/features.yaml

- Needed for testing
Jira-Id: SECO-497

Enable FMO(nats) by default for first boot

---

common/tests/functional/test_mptcp.sh

Functional test cases for MPTCP included.

Test script for MPTCP

---

common/tests/functional/Test-throughput.sh

The test is doing UDP instead of TCP

add a line to allow UDP

---

common/scripts/mesh-11s_nats.sh

Long range tweaks added
HT40 and VHT enabled for high throughput case

Long range and high throughput configs updated

---

modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authClient.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authServer.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/cleanup_cbma.sh
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/launch_cbma.sh
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/macsec/macsec.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/multicast/multicast.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/mutauth.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/secure_channel/secchannel.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/setup_cbma.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/utils.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/verification_tools.py
modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py

Behold fellow reader, the promised PR!
This PR includes some of the old problematic changes (now fixed) discussed in #337 alongside the multiprocessing additions in the old way of calling CBMA and the fixes implemented along the way (all of this squashed in the oldest commit for brevity but still accessible under https://github.com/tiiuae/mesh_com/tree/cbma-mdm-integration/). Another PR will follow this one with the error handling functionality.
Then, this PR also includes individual commits concerning the MDM agent side, which are more relevant for the current state of development.
Have fun! :star2:

CBMA MDM Multiprocessing

---

common/tests/functional/halow/test_halow_nrc7292.sh

halow (nrc7292) functionality test

SECO-3082: halow basic functionality test cases

---

modules/sc-mesh-secure-deployment/src/nats/initd/S90provisioning_agent
modules/sc-mesh-secure-deployment/src/nats/src/comms_provisioning.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_service_discovery.py

Use mDNS discovery to find NATS provisioning server

---

modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py

Catching now possible exceptions.
Jira-Id: SECO-3346

Add exception catch to asyncio loop

---

common/tests/functional/test_fmo_setting.sh

FMO setting test case added

---

common/scripts/mesh-11s_nats.sh
modules/sc-mesh-secure-deployment/src/nats/examples/cli_settings_request.py

Change example script default priority to high_throughput

---

modules/sc-mesh-secure-deployment/src/2_0/features/cbma/tools/monitoring_wpa.py
modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/ldpi/inference.py
modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/main.py
modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/options.py
modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/sniffer/sniffer.py
modules/sc-mesh-secure-deployment/src/2_0/features/ldpi/utils.py
modules/sc-mesh-secure-deployment/src/2_0/main.py

Changes:
- Extract source and destination MAC address from flows
- Report malicious flows IP and MAC address to the decision engine
- Updated LDPI main.py based on 2_0/features/main.py structure: https://ssrc.atlassian.net/wiki/spaces/SC/pages/876445856/2.0+main.py
- Updated 2_0/features/main.py to start LDPI feature

Integrating decision engine with LDPI

---

modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py

- part of the validation is done in comms controller settings code, but empty message check was added to MDM agent side
Jira-Id: SECO-3293

Add validation for the delivered configuration message

---

common/scripts/mesh-11s_nats.sh

Fix correct MTU size for batman interface

---

common/tests/functional/test_osf/osf_common.sh
common/tests/functional/test_osf/test_osf_interface.sh

Move osf test to own folder and refactor it.

---

common/scripts/mesh-11s_nats.sh

WAR: Remove Hostapd socket

---

modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authClient.py
modules/sc-mesh-secure-deployment/src/2_0/features/cbma/auth/authServer.py
modules/sc-mesh-secure-deployment/src/nats/comms_nats_controller.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_if_monitor.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_if_monitor.py

Jira-ID: SECO-3112, SECO-3111
"# FIXME: temporary hard coding for key path" indicates that private key handling will definitely change in the future. I didn't see it reasonable at this point to provide that from from MDM agent as handling of that will anyways change when key is used from HSM.

Use downloaded upper CBMA certificates

---

common/scripts/mesh-11s_nats.sh

Fix problem where nodes were not on same channel after start

---

common/scripts/mesh-11s_nats.sh
modules/utils/docker/entrypoint_nats.sh

NOTE! Needs also a host OS CONFIG_ flag change.
Jira-Id: SECO-3240

Fix AX88719A adapter support

---

common/tests/functional/test_osf/test_osf_config_1.sh
common/tests/functional/test_osf/test_osf_config_2.sh
common/tests/functional/test_osf/test_osf_performance.sh
common/tests/functional/test_osf/test_osf_reset_config.sh
common/tests/functional/test_osf/test_slip_commands.sh
common/tests/functional/test_osf/test_start_iperf3_server.sh

Interface, configuration and performance tests.
SECO-2796

Add OSF BAT tests.

---

common/tests/functional/test_osf/test_udp_commands.sh

Add udp control server test.

---

common/tests/functional/multiradio/test_halow_nrc7292.sh
common/tests/functional/multiradio/test_wifi.sh

Updated scripts for multiradio bat testing (wifi and halow)

SECO-3544: multiradio (wifi and halow) bat test cases updated

---

common/scripts/mesh-11s_nats.sh
common/scripts/mesh-helper.sh
modules/sc-mesh-secure-deployment/src/2_0/features.yaml
modules/sc-mesh-secure-deployment/src/nats/initd/S90APoint
modules/sc-mesh-secure-deployment/src/nats/initd/S90mdm_agent
modules/sc-mesh-secure-deployment/src/nats/mdm_agent.py
modules/sc-mesh-secure-deployment/src/nats/src/cbma_controller.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_command.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_settings.py
modules/sc-mesh-secure-deployment/src/nats/src/validation.py
modules/utils/docker/entrypoint_nats.sh

Contains changes related to tickets: 
SECO-3573, SECO-3578, SECO-3574, SECO-3578, SECO-3806, SECO-3497, SECO-3577, SECO-3802
Relates to tc_distro side PR 195

MS2.0 MDM/CBMA MVP Content

---

common/tests/functional/test_osf/test_osf_config_125K.sh
common/tests/functional/test_osf/test_osf_config_1M_2.sh
common/tests/functional/test_osf/test_osf_config_2M.sh
common/tests/functional/test_osf/test_osf_config_500K.sh
common/tests/functional/test_osf/test_osf_interface.sh
common/tests/functional/test_osf/test_osf_performance_125K.sh
common/tests/functional/test_osf/test_osf_performance_1M.sh
common/tests/functional/test_osf/test_osf_performance_overflow.sh
common/tests/functional/test_osf/test_osf_reset_config.sh
common/tests/functional/test_osf/test_osf_stop_start_driver.sh
common/tests/functional/test_osf/test_slip_commands.sh
common/tests/functional/test_osf/test_start_iperf3_server.sh
common/tests/functional/test_osf/test_udp_commands.sh

SECO-4100
Improve stability of other tests.

Add configurations and performance tests for different osf's PHY.

---

common/tests/functional/test_osf/joinmcastgroup6.py
common/tests/functional/test_osf/osf_common.sh
common/tests/functional/test_osf/sendmcastudp6.py
common/tests/functional/test_osf/test_osf_config_500K.sh
common/tests/functional/test_osf/test_osf_join_mcast_group.sh
common/tests/functional/test_osf/test_osf_performance_1M.sh
common/tests/functional/test_osf/test_osf_read_statistics.sh
common/tests/functional/test_osf/test_osf_send_mcast_udp.sh

SECO-4640
Small improvements of other tests also.

BAT tests for send/receive multicast UDPs

---

modules/sc-mesh-secure-deployment/src/2_0/features/lucius/startup/nats/initd/start_alfred_upper.sh
modules/sc-mesh-secure-deployment/src/nats/initd/start_alfred_upper.sh
modules/sc-mesh-secure-deployment/src/nats/lucius/startup/nats/initd/start_alfred_upper.sh
modules/utils/docker/entrypoint_nats.sh

Remove conflicting bat1 creation in Alfred startup script

---

modules/sc-mesh-secure-deployment/src/nats/mdm_agent.py
modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_command.py
modules/sc-mesh-secure-deployment/src/nats/src/comms_if_monitor.py

Fix MDM Agent process stop

---

common/tools/field_test_logger/field_test_logger.py
common/tools/field_test_logger/wifi_info.py

Add BATMAN_V support to field test logger

---

modules/sc-mesh-secure-deployment/src/nats/conf/default_ms_config.yaml
modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
modules/utils/docker/entrypoint_nats.sh

Jira-IDs: SECO-4779, SECO-4783
Created yaml config to define interface colors and VLAN configs.

Add config file for CBMA

---

modules/sc-mesh-secure-deployment/src/nats/initd/S90APoint

Previous workaround can be removed and AP is started gracefully
Jira-Id: SECO-4883

Fix hostapd_cli

---

modules/sc-mesh-secure-deployment/src/nats/README.md
modules/sc-mesh-secure-deployment/src/nats/requirements.txt
modules/sc-mesh-secure-deployment/src/nats/requirements/requirements.txt
modules/sc-mesh-secure-deployment/src/nats/run_unittests_PC.sh
modules/sc-mesh-secure-deployment/src/nats/src/comms_config_store.py
modules/sc-mesh-secure-deployment/src/nats/src/constants.py
modules/sc-mesh-secure-deployment/src/nats/src/validation.py
modules/sc-mesh-secure-deployment/src/nats/tests/service_discovery_helper.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_command.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_constants.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_controller.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_if_monitor.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_settings.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_status.py
modules/sc-mesh-secure-deployment/src/nats/tests/test_validation.py

- New UnitTests (SECO-4685).
- psutil dependency removed (SECO-4863) to help execution in a target device
- comms_status test fixes (SECO-4874)
Jira-Id: SECO-4685, SECO-4863, SECO-4874

Add more MDM agent UnitTests

---

modules/sc-mesh-secure-deployment/src/nats/initd/S90APoint

Jira-Id: SECO-4998
This reverts commit dab82457d264d39b5b02e71b00dc868f94cad15a.

Revert "Fix hostapd_cli usage"

---

modules/sc-mesh-secure-deployment/src/nats/cbma/scripts/mess/create_mess.sh
modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
modules/sc-mesh-secure-deployment/src/nats/src/constants.py

Change MTU sizes according the interface color

---

modules/sc-mesh-secure-deployment/src/nats/mdm_agent.py

Change MDM agent default None service interface to bat0

---

modules/sc-mesh-secure-deployment/src/nats/mdm_agent.py
modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py
modules/sc-mesh-secure-deployment/src/nats/src/constants.py

Use hardcoded fallback when MDM Server mDNS resolution fails

---

common/scripts/mesh-11s_nats.sh
modules/sc-mesh-secure-deployment/src/nats/initd/S90APoint

Fix AP handling and remove ctrl_interface as not needed for ms2.0

---

common/tools/field_test_logger/field_test_logger.py
common/tools/field_test_logger/wifi_info.py

Field Test Logger update to get halow support working

---

modules/sc-mesh-secure-deployment/src/nats/conf/default_ms_config.yaml

Add usb0 to red_interfaces config list and update bat0/bat1 hop penalty config

---

modules/sc-mesh-secure-deployment/src/nats/conf/default_ms_config.yaml

Do not use CBMA for sap0, sta0 or wfd0

---

modules/sc-mesh-secure-deployment/src/nats/src/cbma_adaptation.py

Fix empty white_interfaces list handling

---

common/tools/field_test_logger/field_test_logger.py
common/tools/field_test_logger/wifi_info.py

field test log update with exp tput and inactive time

field test log update with exp tput and inactive time

---

common/scripts/mesh-11s_nats.sh

Update HaLow Guard Interval to short for better throughput.
Verification completed near TII Masdar area.

Update HaLow Guard Interval for better throughput 
